// creaet event constant
export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAILED = "CREATE_EVENT_FAILED";
export const CREATE_EVENT_RESET = "CREATE_EVENT_RESET";

// update the event state
export const UPDATE_EVENT_REQUEST = "UPDATE_EVENT_REQUEST";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_FAILED = "UPDATE_EVENT_FAILED";
export const UPDATE_EVENT_RESET = "UPDATE_EVENT_RESET";
